### ISSUE TITLE
Git master branch and PyPi Inconsistent

### ISSUE THREAD

**Issue by lazypocket** [metric-learn/metric-learn#112]
I tried installing metric-learn package via pip install metric-learn.
This seems to install an inconsistent version with what I see on Git.
Some examples of the differences is that the PyPi version of BaseMetricLearner class
doesn't inherit from the 'TransformerMixin' class.
Also, the PyPi version of BaseMetricLearner's 'transformer' method transforms by the inverse of the cholesky decomp of matrix M vs. the Git version shows it without the inverse.
Am I installing this the wrong way? It seems that running with the git version gives me more intuitive results/use of methods.

**Comment by perimosocordiae** [comment]
We've been making a lot of progress on the library and plan to push a new point release soon (gh-71), but we haven't gotten there yet.

For now, installing from the master branch is a good idea.

**Comment by lazypocket** [comment]
Thank you very much this is really helpful - would you have a rough estimated timeline of the new release?
