### ISSUE TITLE
No unified function to check the inputs

### ISSUE THREAD

**Issue by bellet** [metric-learn/metric-learn#123]
Right now, almost each algorithm has its own function to prepare/preprocess/check its inputs (verify that there is no duplicate, etc).

Having a single such function which can deal with all inputs and is used by all algorithms would make the code more readable and modular.

**Comment by terrytangyuan** [comment]
Maybe it's also a good chance for us to think about how to handle batches of input or streaming data in case of larger dataset. Probably need to categorize the algorithms to see if it's doable algorithmically. Then we can do something similar to the concept of "input_fn" in [TensorFlow Estimators](https://arxiv.org/pdf/1708.02637.pdf).

**Comment by wdevazelhes** [comment]
@terrytangyuan yes, that's one of the next steps indeed. Nice, I didn't know about `input_fn`, it looks interesting I'll check it out

**Comment by bellet** [comment]
Addressed by #139
