### ISSUE TITLE
transformer_from_metric should be a helper function

### ISSUE THREAD

**Issue by bellet** [metric-learn/metric-learn#146]
#### Description
The function `transformer_from_metric(metric)` which decomposes a PSD matrix into a transformer is currently a method of the class `MahalanobisMixin`. I think the purpose of this function is to do the conversion at the end of the fit algorithm when the latter learns the metric as a PSD matrix instead of a linear transformation. Hence I think it should simply be a helper function.

**Comment by wdevazelhes** [comment]
Yes, I agree, indeed we shouldn't need to have a `MahalanobisMixin` object to be able to use it
