### ISSUE TITLE
[DOC] Organize the API section (Package overview)

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#149]
See comment https://github.com/metric-learn/metric-learn/pull/145#issuecomment-451441725

**EDIT:** This issue is for organizing the API section (e.g. separating the weakly supervised algorithms and the supervised algorithms) (see comment below)

**Comment by bellet** [comment]
I was thinking that the generic class methods could also be briefly demonstrated in the user guide. Maybe for each part (supervised/weakly sup), we could have a first subsection called something like "General API" which explains input data to give to fit as done currently, as well as the `transformer_` attribute and methods like `metric`, `score_pairs` and `transform`. Then the second subsection "Algorithms".

But I also agree that the Package overview section could be better structured

**Comment by wdevazelhes** [comment]
Oh OK yes I agree, it would fit nicely at the beginning of the User guides, I'll open a separate issue for that
