### ISSUE TITLE
Add test coverage badge

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#170]
Running pytest coverage on the package returned 94%, which I believe is a pretty good score (but we'll do even better :) ) 
So I think it would be good to have the badge on the README page

**Comment by bellet** [comment]
Yes. We could also add test coverage to the CI as sklearn to monitor the impact of new PRs and make sure we maintain this good score

**Comment by wdevazelhes** [comment]
Absolutely
