### ISSUE TITLE
Error with modshogun

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#192]
I think there is a problem when using shogun: 
First after I installed shogun (the last version, I tried to install with conda forge and also pip), I cannot  `import modshogun` (it throws a package not found error), but instead I can `import shogun`. Maybe I messed up somewhere in the install process or maybe the newest version have a different name or sth..

Even if I change the code with `import shogun` instead of `import modshogun`, there is another error when doing: 

```python
from metric_learn import LMNN
from sklearn.datasets import make_blobs
X, y = make_blobs(n_features=2)
X.shape
lmnn = LMNN()
lmnn.fit(X,y)
```

And it returns the following error:

```pytb
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_MulticlassLabels'.
  Possible C/C++ prototypes are:
    shogun::CMulticlassLabels::CMulticlassLabels()
    shogun::CMulticlassLabels::CMulticlassLabels(int32_t)
    shogun::CMulticlassLabels::CMulticlassLabels(shogun::SGVector< float64_t >)
    shogun::CMulticlassLabels::CMulticlassLabels(shogun::CFile *)
    shogun::CMulticlassLabels::CMulticlassLabels(shogun::CBinaryLabels *)
```

**Comment by bellet** [comment]
It is probably a version issue?

**Comment by perimosocordiae** [comment]
When I set up shogun initially, I built it from source and enabled the "python_modular" interface.

It seems like things have changed since then: https://github.com/shogun-toolbox/shogun/pull/3898

We should update our usage of Shogun, or remove it entirely if it's going to be a pain.

**Comment by bellet** [comment]
Also it does not seem like Shogun_LMNN can do dimensionality reduction, which is at odds with the objective of #193. So maybe it is easier to remove it? We could try to work on an optimized version of LMNN later
