### ISSUE TITLE
transformer_ or components_ ?

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#196]
Currently we call the transformer matrix `transformer_` for all algorithms. However in scikit-learn they mostly use `components_` for the (quite) same object. I think we might have discussed this with @bellet and @nvauquie but I'm not sure at all, and don't remember what we decided
If it's better, it would be good to change this before the release to avoid a deprecation cycle

**Comment by bellet** [comment]
Indeed this seems more consistent to rename into `components_` for `MahalanobisMixin`
