### ISSUE TITLE
Update covariance

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#204]
In the `Covariance` algorithm, we currently do an inverse of the covariance matrix, and the latter could be singular. We need to decide whether to return an error or return the pseudo inverse in this case.

**Comment by bellet** [comment]
I think we should use the pseudo-inverse, which is a common thing to do, see for instance the following link (sorry for the lack of better reference):
https://stats.stackexchange.com/questions/37743/singular-covariance-matrix-in-mahalanobis-distance-in-matlab
