### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by ab-anssi** [metric-learn/metric-learn#209]
Have you planed to release a new version of metric-learn shortly ?

The current version (0.4.0) does not work with the latest version of scikit-learn (0.21.1). 

`
File "metric_learn/sdml.py", line 15, in <module>
    from sklearn.utils.extmath import pinvh
ImportError: cannot import name 'pinvh'
`

**Comment by wdevazelhes** [comment]
Hi @ab-anssi, yes, we are planning to release 0.5.0 as soon as possible (by the end of the month ideally). In the meantime, you can use the master version, which should be compatible with the latest scikit-learn version (you should be able to install it from github doing:
 `pip install git+https://github.com/metric-learn/metric-learn`)

**Comment by ab-anssi** [comment]
Hi @wdevazelhes . 
Thanks for your quick answer. I am currently using the master version (and it works !), but it would be much better to have a new version released. I am looking forward to it !
Thanks for your help.
