### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#212]
We need to update this link, which appears not to work anymore, and maybe check if it happens for other links: 
https://machinelearning.wustl.edu/mlpapers/paper_files/icml2007_DavisKJSD07.pdf

**Comment by perimosocordiae** [comment]
Looks like this link is a good replacement:
http://www.cs.utexas.edu/users/pjain/pubs/metriclearning_icml.pdf

**Comment by bellet** [comment]
Ideally we should use the links on the official proceedings which are less likely to break than links from author pages, in this case
https://icml.cc/imls/conferences/2007/proceedings/papers/404.pdf
