### ISSUE TITLE
Update docs for *_Supervised classes

### ISSUE THREAD

**Issue by perimosocordiae** [metric-learn/metric-learn#22]
PR #19 introduced supervised variants of some algorithms, along with a module for generating constraints from supervised labels. These will need to be documented before the next release.

**Comment by bhargavvader** [comment]
Has this been done? The docs for the supervised learning bits seem pretty okay to me!
Also, wanted to know a little bit more about your comment on PR #19 . You mentioned - `From my perspective, the main use-cases for metric learning are unsupervised/semisupervised learning. `

Aren't all metric learning algorithms at the very least weakly supervised? 
Sorry if this is off-topic, just wanted to make sure - I was under the impression you cannot in any way get rid of the labels or side information when going about doing metric learning.

I am working with unlabelled data and sort of hacking it to make a crude 'labelling' before applying a metric learning algorithm - so it would be great to know of ways to make it less supervised!

**Comment by perimosocordiae** [comment]
There are docstrings for the supervised variants now, but I'd like to have something in the documentation explaining how they fit together with their normal variants. I'll look into writing it the next time I prepare a release for PyPI (not for a few weeks, realistically).

Regarding the supervised/unsupervised distinction: you're right that we need some sort of side information, otherwise we wouldn't have anything to go on. That side information could take the form of an assumption, though, rather than explicit labels. For example, PCA could be viewed as a kind of unsupervised metric learning. It's important to remember that there's no free lunch, though; the assumption you make is still a kind of supervision.

**Comment by bhargavvader** [comment]
Makes sense, thanks!
