### ISSUE TITLE
How to save and restore weights of a weakly-supervised algorithm

### ISSUE THREAD

**Issue by m4nuC** [metric-learn/metric-learn#240]
Hi,

Is there an API to export a model's weights after some iterations on a weakly supervised algorithms (for example MMC) and load them back later on? 

I've seen `get_mahalanobis_matrix()` but that seems to exist only on supervised algos?

Thanks a lot for this great package.

Emmanuel

**Comment by wdevazelhes** [comment]
Hi @m4nuC, thanks for your message

`get_mahalanobis_matrix` should be able to be used even for weakly supervised / unsupervised algos. Do you have a toy example where it doesn't work ? 

Another option is to pickle your model after training, like a regular scikit-learn estimator: https://scikit-learn.org/stable/modules/model_persistence.html
Then you would export it somewhere, unpickle it, and it should have the weights loaded, ready for a transform/predict step

**Comment by m4nuC** [comment]
Thanks, @wdevazelhes, I don't have a toy example atm but I am looking into implementing this in the following weeks. Pickling it seems like the right option.
