### ISSUE TITLE
MMC : too many indices for array

### ISSUE THREAD

**Issue by GuillaumeDesforges** [metric-learn/metric-learn#87]
I am trying to use the MMC, which does not seem to be documented yet.

Looking at the code I thought that if I had
`pos_pairs = [(i1, i2) for i1 in range(N1) for i2 in range(N2) if condition(i1, i2)]`
and
`neg_pairs = [(i1, i2) for i1 in range(N1) for i2 in range(N2) if not condition(i1, i2)]`
I would be able to pass contraints as :
```python
a, b = tuple(zip(*pos_pairs))
c, d = tuple(zip(*neg_pairs))
contraints = (a, b, c, d)
```

My data is `X = np.stack([I.descriptor for I in I_list])` where `I.descriptor` is an array of dimension *(9000,)*.

Then doing
```python
metric = MMC(diagonal=True)
metric.fit(X, contraints)
```

raises an error :
```
metric.fit(X, (a, b, c, d))
File "/usr/lib/python3.6/site-packages/metric_learn-0.4.0-py3.6.egg/metric_learn/mmc.py", line 72, in fit
File "/usr/lib/python3.6/site-packages/metric_learn-0.4.0-py3.6.egg/metric_learn/mmc.py", line 84, in _process_inputs
IndexError: too many indices for array
```

But then again, I have `a` and `b` so that `a[i]` and `b[i]` are such that they are indices of elements `X[a[i]]` and `X[b[i]]` of stacked X that are supposed to be close (and far for `c` and `d`).

**Comment by perimosocordiae** [comment]
Sorry to have left this for so long without a response. In case you weren't able to fix this already: can you share the shape of `X`, and how it relates to `N1` and `N2`?

In general, if `X.shape` is `(N, D)`, then you want all elements in each constraint array (`a`, `b`, `c`, and `d`) to be between 0 and `N`.

**Comment by GuillaumeDesforges** [comment]
Sorry, I no longer follow the project that wanted to use this library...
