### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by wdevazelhes** [metric-learn/metric-learn#93]
Scipy version 1.1.0 has been recently released, and is the one now installed when Travis CI runs tests  (see for instance the difference between this log (more recent one, with scipy 1.1.0):  https://travis-ci.org/metric-learn/metric-learn/jobs/373932172#L466 , and this one (old one, with scipy 1.0.0):  https://travis-ci.org/metric-learn/metric-learn/jobs/346909164#L462).

The thing is that now scipy ``eigsh``, if k >= n_features, instead of raising a ``ValueError``, tries to call ``eigh`` (see the two different versions: newest one: https://github.com/scipy/scipy/blame/dfb0cc2e5946e81a7ccefbe101a72b0f96317a6e/scipy/sparse/linalg/eigen/arpack/arpack.py#L1550 , oldest one:  https://github.com/scipy/scipy/blame/768251cd14ccbf467a8725e5476e35fb2735ee4a/scipy/sparse/linalg/eigen/arpack/arpack.py#L1521) (this strategy is basically what is coded is coded in LFDA's ``_eigh`` method, see: https://github.com/metric-learn/metric-learn/blob/master/metric_learn/lfda.py#L142). What happens in the new build is that we go through ``eighs``, then it calls ``eigh``, and there is throws the LinAlgError (that was catched and continued before in LFDA's code (here: https://github.com/metric-learn/metric-learn/blob/master/metric_learn/lfda.py#L146)), but we are still in the ``try: eigsh``, and LinAlgErrors are not catched there.

I guess the fix would depend on whether we want to do backward compatibility ? If so, we could maybe just add the LinAlgError to the list of errors checked, like this: 
```python
def _eigh(a, b, dim):
  try:
    return scipy.sparse.linalg.eigsh(a, k=dim, M=b, which='LA')
  except (ValueError, np.linalg.LinAlgError, scipy.sparse.linalg.ArpackNoConvergence):
    pass
  try:
    return scipy.linalg.eigh(a, b)
  except np.linalg.LinAlgError:
    pass
  return scipy.linalg.eig(a, b)
```

Otherwise, as now the case with ValueError is already dealt with inside scipy's eighs, we could simplify the code as follows: 

```python
def _eigh(a, b, dim):
  try:
    return scipy.sparse.linalg.eigsh(a, k=dim, M=b, which='LA')
  except (np.linalg.LinAlgError, scipy.sparse.linalg.ArpackNoConvergence):
    pass
  return scipy.linalg.eig(a, b)
```

Indeed I think we could get rid of ValueError because (correct me if I am wrong) it is raised in only two cases by eigsh: 
- if k<=0 (this case cannot happen because k is n_dims which is checked to be strictly positive in _process_inputs
- if k>=n_features (the dim of original samples). This case is the one discussed, already dealt with inside scipy's eigsh.

**Comment by perimosocordiae** [comment]
Let's try to keep back-compat if possible. I should have caught this earlier, as I was the one who reviewed and mergedthe scipy change that caused it (https://github.com/scipy/scipy/pull/7004)!

How about this approach:

```python
def _eigh(a, b, dim):
  try:
    return scipy.sparse.linalg.eigsh(a, k=dim, M=b, which='LA')
  except np.linalg.LinAlgError:
    pass  # scipy already tried eigh for us
  except (ValueError, scipy.sparse.linalg.ArpackNoConvergence):
    try:
      return scipy.linalg.eigh(a, b)
    except np.linalg.LinAlgError:
      pass
  return scipy.linalg.eig(a, b)
```

**Comment by wdevazelhes** [comment]
I agree with this approach, indeed my first proposal would pass twice through eigh :p Also the comment makes the modification way clearer. I just made a PR with your proposal: https://github.com/metric-learn/metric-learn/pull/94
